dataset:
  root_path:  data/mls_6h_reseg/

preprocessing:
  val_size: 8
  sampling_rate: 16000

  text:
    language: "en"
    max_length: 4096
  stft:
    filter_length: 1024
    hop_length: 160
    win_length: 1024
  mel:
    n_mel_channels: 128
    mel_fmin: 0
    mel_fmax: 8000 # please set to 8000 for HiFi-GAN vocoder, set to null for MelGAN vocoder
  pitch:
    feature_level: "phoneme" # support 'phoneme' or 'frame'
    normalization: True
  energy:
    feature_level: "phoneme" # support 'phoneme' or 'frame'
    normalization: True
